name: Build Multi-Platform

on:
  push:
    branches: [ main ]

jobs:

  build-windows:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install deps
        run: |
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build EXE
        run: |
          pyinstaller --onefile --windowed ^
            --name ModernArchiver ^
            --icon=icon.ico ^
            --collect-all PyQt6 ^
            app.py

      # Installer
      - name: Install Inno Setup
        run: choco install innosetup -y

      - name: Build Installer
        run: |
          iscc installer.iss

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: build-${{ github.run_number }}
          name: Build ${{ github.run_number }}
          prerelease: true
          files: |
            dist/ModernArchiver.exe
            Output/ModernArchiverSetup.exe

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - run: |
          pip install -r requirements.txt
          pip install pyinstaller

      - run: |
          pyinstaller --onefile app.py

      - run: |
          mkdir AppDir
          cp dist/ModernArchiver AppDir/

      - run: |
          wget -q https://github.com/AppImage/AppImageKit/releases/latest/download/appimagetool-x86_64.AppImage
          chmod +x appimagetool-x86_64.AppImage
          ./appimagetool-x86_64.AppImage AppDir

      - uses: softprops/action-gh-release@v2
        with:
          tag_name: build-${{ github.run_number }}
          files: ModernArchiver*.AppImage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - run: |
          pip install -r requirements.txt
          pip install pyinstaller

      - run: |
          pyinstaller --windowed app.py

      - run: |
          hdiutil create ModernArchiver.dmg -srcfolder dist/

      - uses: softprops/action-gh-release@v2
        with:
          tag_name: build-${{ github.run_number }}
          files: ModernArchiver.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}