# .github/workflows/build-and-release.yml

name: Build and Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    # --- ВОТ ИСПРАВЛЕНИЕ ---
    # Предоставляем права на запись, чтобы экшен мог создавать релизы
    permissions:
      contents: write
    # -------------------------

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build executable with PyInstaller
        run: pyinstaller --onefile --windowed --name "ModernArchiver" modern_archiver.py --hidden-import=sv_ttk

      - name: Upload Build Artifact
        if: "!startsWith(github.ref, 'refs/tags/')"
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: dist/ModernArchiver.exe

      - name: Create Release and Upload Asset 
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: false
          name: Release ${{ github.ref_name }}
          generate_release_notes: true
          files: |
            dist/ModernArchiver.exe